
import java.util.ArrayList;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Javi
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    GestorConexion ges = new GestorConexion();

    public VentanaPrincipal() {
        initComponents();
        deshabilitarBotones();
        setIconImage(new ImageIcon(getClass().getResource("/img/icons8-cd-30.png")).getImage());//cambia el icono del jFrame
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaQuerys = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabelManejo = new javax.swing.JLabel();
        jButton_Conectar = new javax.swing.JButton();
        jButton_Desconectar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_Selects = new javax.swing.JPanel();
        jLabel_SelectEquipo = new javax.swing.JLabel();
        jLabel_SelectDatos = new javax.swing.JLabel();
        jLabel_SelectSuperBowls = new javax.swing.JLabel();
        jButton_ConsultaEquipos = new javax.swing.JButton();
        jButton_ConsultaDatos = new javax.swing.JButton();
        jButton_ConsultaSB = new javax.swing.JButton();
        jLabel_SelectSuperBowls1 = new javax.swing.JLabel();
        jTextField_BuscarEquipo = new javax.swing.JTextField();
        jButton_Buscar = new javax.swing.JButton();
        jPanel_Updates = new javax.swing.JPanel();
        jComboBox_Equipos = new javax.swing.JComboBox<>();
        jLabel_SelecionarEquipo = new javax.swing.JLabel();
        jLabel_CambiarNombre = new javax.swing.JLabel();
        jLabel_CambiarCiudad = new javax.swing.JLabel();
        jLabel_CambiarEstadio = new javax.swing.JLabel();
        jTextField_UpdateNombre = new javax.swing.JTextField();
        jTextField_UpdateCiudad = new javax.swing.JTextField();
        jTextField_UpdateEstadio = new javax.swing.JTextField();
        jButton_UPDATEEquipo = new javax.swing.JButton();
        jPanel_Inserts = new javax.swing.JPanel();
        jTabbedPane_Inserts = new javax.swing.JTabbedPane();
        jPanel_InsertarDatos = new javax.swing.JPanel();
        jPanel_InsertarSuperBowls = new javax.swing.JPanel();
        jPanel_InsertarEquipos = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        jDialog1.setResizable(false);
        jDialog1.setSize(new java.awt.Dimension(500, 650));

        jTextAreaQuerys.setEditable(false);
        jTextAreaQuerys.setBackground(new java.awt.Color(0, 0, 102));
        jTextAreaQuerys.setColumns(20);
        jTextAreaQuerys.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTextAreaQuerys.setForeground(new java.awt.Color(255, 255, 255));
        jTextAreaQuerys.setRows(5);
        jScrollPane1.setViewportView(jTextAreaQuerys);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabelManejo.setBackground(new java.awt.Color(51, 153, 255));
        jLabelManejo.setText("MANEJAR CONEXIÓN CON LA BBDD");
        jLabelManejo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelManejo.setOpaque(true);

        jButton_Conectar.setBackground(new java.awt.Color(51, 153, 255));
        jButton_Conectar.setText("Conectar/Actualizar");
        jButton_Conectar.setBorder(new javax.swing.border.MatteBorder(null));
        jButton_Conectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConectarActionPerformed(evt);
            }
        });

        jButton_Desconectar.setBackground(new java.awt.Color(51, 153, 255));
        jButton_Desconectar.setText("Desconectar");
        jButton_Desconectar.setBorder(new javax.swing.border.MatteBorder(null));
        jButton_Desconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DesconectarActionPerformed(evt);
            }
        });

        jTabbedPane1.setBackground(new java.awt.Color(0, 102, 102));

        jPanel_Selects.setBackground(new java.awt.Color(0, 153, 204));
        jPanel_Selects.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel_SelectEquipo.setBackground(new java.awt.Color(102, 153, 255));
        jLabel_SelectEquipo.setText("CONSULTAR EQUIPOS");
        jLabel_SelectEquipo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_SelectEquipo.setOpaque(true);

        jLabel_SelectDatos.setBackground(new java.awt.Color(102, 153, 255));
        jLabel_SelectDatos.setText("CONSULTAR DATOS DEL EQUIPO");
        jLabel_SelectDatos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_SelectDatos.setOpaque(true);

        jLabel_SelectSuperBowls.setBackground(new java.awt.Color(102, 153, 255));
        jLabel_SelectSuperBowls.setText("CONSULTAR SUPER BOWLS DEL EQUIPO");
        jLabel_SelectSuperBowls.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_SelectSuperBowls.setOpaque(true);

        jButton_ConsultaEquipos.setBackground(new java.awt.Color(0, 204, 204));
        jButton_ConsultaEquipos.setText("EJECUTAR CONSULTA");
        jButton_ConsultaEquipos.setBorder(new javax.swing.border.MatteBorder(null));
        jButton_ConsultaEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConsultaEquiposActionPerformed(evt);
            }
        });

        jButton_ConsultaDatos.setBackground(new java.awt.Color(0, 204, 204));
        jButton_ConsultaDatos.setText("EJECUTAR CONSULTA");
        jButton_ConsultaDatos.setBorder(new javax.swing.border.MatteBorder(null));
        jButton_ConsultaDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConsultaDatosActionPerformed(evt);
            }
        });

        jButton_ConsultaSB.setBackground(new java.awt.Color(0, 204, 204));
        jButton_ConsultaSB.setText("EJECUTAR CONSULTA");
        jButton_ConsultaSB.setBorder(new javax.swing.border.MatteBorder(null));
        jButton_ConsultaSB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConsultaSBActionPerformed(evt);
            }
        });

        jLabel_SelectSuperBowls1.setBackground(new java.awt.Color(102, 153, 255));
        jLabel_SelectSuperBowls1.setText("BUSCAR EQUIPO");
        jLabel_SelectSuperBowls1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_SelectSuperBowls1.setOpaque(true);

        jTextField_BuscarEquipo.setBackground(new java.awt.Color(0, 51, 102));
        jTextField_BuscarEquipo.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_BuscarEquipo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton_Buscar.setBackground(new java.awt.Color(0, 204, 204));
        jButton_Buscar.setText("EJECUTAR CONSULTA");
        jButton_Buscar.setBorder(new javax.swing.border.MatteBorder(null));
        jButton_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_SelectsLayout = new javax.swing.GroupLayout(jPanel_Selects);
        jPanel_Selects.setLayout(jPanel_SelectsLayout);
        jPanel_SelectsLayout.setHorizontalGroup(
            jPanel_SelectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SelectsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_SelectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_SelectSuperBowls1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_SelectSuperBowls, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(jLabel_SelectDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_SelectEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_SelectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_SelectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton_ConsultaEquipos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                        .addComponent(jButton_ConsultaDatos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_ConsultaSB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTextField_BuscarEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Buscar, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_SelectsLayout.setVerticalGroup(
            jPanel_SelectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SelectsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_SelectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_SelectEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_ConsultaEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_SelectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_SelectDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_ConsultaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_SelectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_SelectSuperBowls, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_ConsultaSB, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_SelectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_SelectSuperBowls1, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jButton_Buscar, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jTextField_BuscarEquipo))
                .addContainerGap(231, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CONSULTAR BBDD", jPanel_Selects);

        jPanel_Updates.setBackground(new java.awt.Color(0, 153, 204));
        jPanel_Updates.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jComboBox_Equipos.setBackground(new java.awt.Color(0, 51, 102));
        jComboBox_Equipos.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox_Equipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel_SelecionarEquipo.setBackground(new java.awt.Color(102, 153, 255));
        jLabel_SelecionarEquipo.setText("SELECCIONAR EQUIPO A MODIFICAR");
        jLabel_SelecionarEquipo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_SelecionarEquipo.setOpaque(true);

        jLabel_CambiarNombre.setBackground(new java.awt.Color(102, 153, 255));
        jLabel_CambiarNombre.setText("NOMBRE NUEVO");
        jLabel_CambiarNombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_CambiarNombre.setOpaque(true);

        jLabel_CambiarCiudad.setBackground(new java.awt.Color(102, 153, 255));
        jLabel_CambiarCiudad.setText("CIUDAD NUEVA");
        jLabel_CambiarCiudad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_CambiarCiudad.setOpaque(true);

        jLabel_CambiarEstadio.setBackground(new java.awt.Color(102, 153, 255));
        jLabel_CambiarEstadio.setText("ESTADIO NUEVO");
        jLabel_CambiarEstadio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_CambiarEstadio.setOpaque(true);

        jTextField_UpdateNombre.setBackground(new java.awt.Color(0, 51, 102));
        jTextField_UpdateNombre.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_UpdateNombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextField_UpdateCiudad.setBackground(new java.awt.Color(0, 51, 102));
        jTextField_UpdateCiudad.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_UpdateCiudad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextField_UpdateEstadio.setBackground(new java.awt.Color(0, 51, 102));
        jTextField_UpdateEstadio.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_UpdateEstadio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton_UPDATEEquipo.setBackground(new java.awt.Color(0, 204, 204));
        jButton_UPDATEEquipo.setText("EJECUTAR");
        jButton_UPDATEEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UPDATEEquipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_UpdatesLayout = new javax.swing.GroupLayout(jPanel_Updates);
        jPanel_Updates.setLayout(jPanel_UpdatesLayout);
        jPanel_UpdatesLayout.setHorizontalGroup(
            jPanel_UpdatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_UpdatesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_UpdatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_CambiarEstadio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_CambiarCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_CambiarNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_SelecionarEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_UpdatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox_Equipos, 0, 186, Short.MAX_VALUE)
                    .addComponent(jTextField_UpdateNombre)
                    .addComponent(jTextField_UpdateCiudad)
                    .addComponent(jTextField_UpdateEstadio)
                    .addComponent(jButton_UPDATEEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                .addGap(133, 133, 133))
        );
        jPanel_UpdatesLayout.setVerticalGroup(
            jPanel_UpdatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_UpdatesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_UpdatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox_Equipos)
                    .addComponent(jLabel_SelecionarEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_UpdatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_CambiarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_UpdateNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_UpdatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_CambiarCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jTextField_UpdateCiudad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_UpdatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_CambiarEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_UpdateEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_UPDATEEquipo)
                .addContainerGap(217, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("MODIFICAR EQUIPOS", jPanel_Updates);

        jPanel_Inserts.setBackground(new java.awt.Color(0, 153, 204));
        jPanel_Inserts.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel_InsertarDatos.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel_InsertarDatosLayout = new javax.swing.GroupLayout(jPanel_InsertarDatos);
        jPanel_InsertarDatos.setLayout(jPanel_InsertarDatosLayout);
        jPanel_InsertarDatosLayout.setHorizontalGroup(
            jPanel_InsertarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );
        jPanel_InsertarDatosLayout.setVerticalGroup(
            jPanel_InsertarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
        );

        jTabbedPane_Inserts.addTab("DATOS DE EQUIPO", jPanel_InsertarDatos);

        jPanel_InsertarSuperBowls.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel_InsertarSuperBowlsLayout = new javax.swing.GroupLayout(jPanel_InsertarSuperBowls);
        jPanel_InsertarSuperBowls.setLayout(jPanel_InsertarSuperBowlsLayout);
        jPanel_InsertarSuperBowlsLayout.setHorizontalGroup(
            jPanel_InsertarSuperBowlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );
        jPanel_InsertarSuperBowlsLayout.setVerticalGroup(
            jPanel_InsertarSuperBowlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
        );

        jTabbedPane_Inserts.addTab("SUPER BOWLS DEL EQUIPO", jPanel_InsertarSuperBowls);

        jPanel_InsertarEquipos.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel_InsertarEquiposLayout = new javax.swing.GroupLayout(jPanel_InsertarEquipos);
        jPanel_InsertarEquipos.setLayout(jPanel_InsertarEquiposLayout);
        jPanel_InsertarEquiposLayout.setHorizontalGroup(
            jPanel_InsertarEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );
        jPanel_InsertarEquiposLayout.setVerticalGroup(
            jPanel_InsertarEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
        );

        jTabbedPane_Inserts.addTab("EQUIPO", jPanel_InsertarEquipos);

        javax.swing.GroupLayout jPanel_InsertsLayout = new javax.swing.GroupLayout(jPanel_Inserts);
        jPanel_Inserts.setLayout(jPanel_InsertsLayout);
        jPanel_InsertsLayout.setHorizontalGroup(
            jPanel_InsertsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_Inserts)
        );
        jPanel_InsertsLayout.setVerticalGroup(
            jPanel_InsertsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_Inserts)
        );

        jTabbedPane1.addTab("INSERTAR EN LA BBDD", jPanel_Inserts);

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("BORRAR TUPLAS", jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTabbedPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelManejo, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Conectar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_Desconectar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelManejo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Conectar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Desconectar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_DesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DesconectarActionPerformed
        ges.cerrar_conexion();
        deshabilitarBotones();
    }//GEN-LAST:event_jButton_DesconectarActionPerformed

    //este botón sirve a su vez para conectar con el servidor/bbdd como para actualizar la conexión en caso de cambios
    private void jButton_ConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConectarActionPerformed

        if (ges.GestorConexion() == 0) {
            System.out.println("Conexión establecida correctamente");
            rellenarBoxEquipos();
            conectar();
        } else if (ges.GestorConexion() == 1) {
            System.out.println("No fue posible establecer una conexión");
        } else {
            System.out.println("Error en la conexion");
        }
    }//GEN-LAST:event_jButton_ConectarActionPerformed

    private void jButton_ConsultaEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConsultaEquiposActionPerformed
        jDialog1.setVisible(true);
        jTextAreaQuerys.setText(ges.selectEquipos());
    }//GEN-LAST:event_jButton_ConsultaEquiposActionPerformed

    private void jButton_ConsultaDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConsultaDatosActionPerformed
        jDialog1.setVisible(true);
        jTextAreaQuerys.setText(ges.selectDatos());
    }//GEN-LAST:event_jButton_ConsultaDatosActionPerformed

    private void jButton_ConsultaSBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConsultaSBActionPerformed
        jDialog1.setVisible(true);
        jTextAreaQuerys.setText(ges.selectSB());
    }//GEN-LAST:event_jButton_ConsultaSBActionPerformed

    private void jButton_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuscarActionPerformed
        jDialog1.setVisible(true);
        jTextAreaQuerys.setText(ges.buscarEquipo(jTextField_BuscarEquipo.getText()));
        jTextField_BuscarEquipo.setText("");
    }//GEN-LAST:event_jButton_BuscarActionPerformed

    private void jButton_UPDATEEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UPDATEEquipoActionPerformed
        String idEquipo = (String) jComboBox_Equipos.getSelectedItem();
        int equipo = Integer.parseInt(idEquipo.split(" ")[0]);
        ges.modificarEquipo(jTextField_UpdateNombre.getText(), jTextField_UpdateCiudad.getText(), jTextField_UpdateEstadio.getText(), equipo);
        jTextField_UpdateNombre.setText("");
        jTextField_UpdateCiudad.setText("");
        jTextField_UpdateEstadio.setText("");
    }//GEN-LAST:event_jButton_UPDATEEquipoActionPerformed

    //este método rellena los combobox relacionados a los equipos con el método arraylist creado en la clase del gestor
    private void rellenarBoxEquipos() {
        //primero eimina los datos por defecto para llenarlos con los datos deseados
        jComboBox_Equipos.removeAllItems();
        ArrayList<String> listaEquipos = new ArrayList<String>();//para la foreign key de album en canciones
        listaEquipos = ges.comboBoxEquipos();
        for (int i = 0; i < listaEquipos.size(); i++) {
            jComboBox_Equipos.addItem(listaEquipos.get(i));
        }
    }

    //este método deshabilita todos los botones y vacia los combobox en caso de no estar conectado a la bbdd o de haber
    //finalizado la conexión
    private void deshabilitarBotones() {
        jButton_Desconectar.setEnabled(false);

    }

    //este método habilita todos los botones de la interfaz, usado despues de haber conectado con la base de datos
    private void conectar() {

        jButton_Desconectar.setEnabled(true);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Buscar;
    private javax.swing.JButton jButton_Conectar;
    private javax.swing.JButton jButton_ConsultaDatos;
    private javax.swing.JButton jButton_ConsultaEquipos;
    private javax.swing.JButton jButton_ConsultaSB;
    private javax.swing.JButton jButton_Desconectar;
    private javax.swing.JButton jButton_UPDATEEquipo;
    private javax.swing.JComboBox<String> jComboBox_Equipos;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabelManejo;
    private javax.swing.JLabel jLabel_CambiarCiudad;
    private javax.swing.JLabel jLabel_CambiarEstadio;
    private javax.swing.JLabel jLabel_CambiarNombre;
    private javax.swing.JLabel jLabel_SelecionarEquipo;
    private javax.swing.JLabel jLabel_SelectDatos;
    private javax.swing.JLabel jLabel_SelectEquipo;
    private javax.swing.JLabel jLabel_SelectSuperBowls;
    private javax.swing.JLabel jLabel_SelectSuperBowls1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_InsertarDatos;
    private javax.swing.JPanel jPanel_InsertarEquipos;
    private javax.swing.JPanel jPanel_InsertarSuperBowls;
    private javax.swing.JPanel jPanel_Inserts;
    private javax.swing.JPanel jPanel_Selects;
    private javax.swing.JPanel jPanel_Updates;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane_Inserts;
    private javax.swing.JTextArea jTextAreaQuerys;
    private javax.swing.JTextField jTextField_BuscarEquipo;
    private javax.swing.JTextField jTextField_UpdateCiudad;
    private javax.swing.JTextField jTextField_UpdateEstadio;
    private javax.swing.JTextField jTextField_UpdateNombre;
    // End of variables declaration//GEN-END:variables

}
