
import java.util.ArrayList;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Javi
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    GestorConexion ges = new GestorConexion();

    public VentanaPrincipal() {
        initComponents();
        deshabilitarBotones();
        setIconImage(new ImageIcon(getClass().getResource("/img/icono.png")).getImage());//cambia el icono del jFrame
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaQuerys = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabelManejo = new javax.swing.JLabel();
        jButton_Conectar = new javax.swing.JButton();
        jButton_Desconectar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_Selects = new javax.swing.JPanel();
        jLabel_SelectEquipo = new javax.swing.JLabel();
        jLabel_SelectDatos = new javax.swing.JLabel();
        jLabel_SelectSuperBowls = new javax.swing.JLabel();
        jButton_ConsultaEquipos = new javax.swing.JButton();
        jButton_ConsultaDatos = new javax.swing.JButton();
        jButton_ConsultaSB = new javax.swing.JButton();
        jLabel_SelectSuperBowls1 = new javax.swing.JLabel();
        jTextField_BuscarEquipo = new javax.swing.JTextField();
        jButton_Buscar = new javax.swing.JButton();
        jPanel_Updates = new javax.swing.JPanel();
        jComboBox_Equipos = new javax.swing.JComboBox<>();
        jLabel_SelecionarEquipo = new javax.swing.JLabel();
        jLabel_CambiarNombre = new javax.swing.JLabel();
        jLabel_CambiarCiudad = new javax.swing.JLabel();
        jLabel_CambiarEstadio = new javax.swing.JLabel();
        jTextField_UpdateNombre = new javax.swing.JTextField();
        jTextField_UpdateCiudad = new javax.swing.JTextField();
        jTextField_UpdateEstadio = new javax.swing.JTextField();
        jButton_UPDATEEquipo = new javax.swing.JButton();
        jPanel_Inserts = new javax.swing.JPanel();
        jTabbedPane_Inserts = new javax.swing.JTabbedPane();
        jPanel_InsertarDatos = new javax.swing.JPanel();
        jLabel_Conferencia = new javax.swing.JLabel();
        jLabel_Division = new javax.swing.JLabel();
        jLabel_Propietario = new javax.swing.JLabel();
        jLabel_Fundacion = new javax.swing.JLabel();
        jLabel_EntradaNFL = new javax.swing.JLabel();
        jLabel_CodIDDATOS = new javax.swing.JLabel();
        jTextField_Conferencia = new javax.swing.JTextField();
        jTextField_Division = new javax.swing.JTextField();
        jTextField_Propietario = new javax.swing.JTextField();
        jTextField_Fundacion = new javax.swing.JTextField();
        jTextField_EntradaNFL = new javax.swing.JTextField();
        jTextField_CodIDDATOS = new javax.swing.JTextField();
        jButton_InsertarDatos = new javax.swing.JButton();
        jPanel_InsertarSuperBowls = new javax.swing.JPanel();
        jLabel_FechaVict = new javax.swing.JLabel();
        jLabel_CantidadVict = new javax.swing.JLabel();
        jLabel_CodIDSB = new javax.swing.JLabel();
        jTextField_FechaVict = new javax.swing.JTextField();
        jTextField_CantidadVict = new javax.swing.JTextField();
        jTextField_CodIDSB = new javax.swing.JTextField();
        jButton_InsertarSB = new javax.swing.JButton();
        jPanel_InsertarEquipos = new javax.swing.JPanel();
        jLabel_Nombre = new javax.swing.JLabel();
        jLabel_Ciudad = new javax.swing.JLabel();
        jLabel_Estadio = new javax.swing.JLabel();
        jLabel_CodIDEQUIPO = new javax.swing.JLabel();
        jLabel_Datos = new javax.swing.JLabel();
        jLabel_SuperBowls = new javax.swing.JLabel();
        jTextField_Nombre = new javax.swing.JTextField();
        jTextField_Ciudad = new javax.swing.JTextField();
        jTextField_Estadio = new javax.swing.JTextField();
        jTextField_CodIDEQUIPO = new javax.swing.JTextField();
        jComboBox_Datos = new javax.swing.JComboBox<>();
        jComboBox_SuperBowls = new javax.swing.JComboBox<>();
        jButton_InsertarEquipo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel_BorrarEquipo = new javax.swing.JLabel();
        jTextField_BorrarEquipo = new javax.swing.JTextField();
        jButton_Borrar = new javax.swing.JButton();

        jDialog1.setResizable(false);
        jDialog1.setSize(new java.awt.Dimension(500, 650));

        jTextAreaQuerys.setEditable(false);
        jTextAreaQuerys.setBackground(new java.awt.Color(0, 0, 102));
        jTextAreaQuerys.setColumns(20);
        jTextAreaQuerys.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTextAreaQuerys.setForeground(new java.awt.Color(255, 255, 255));
        jTextAreaQuerys.setRows(5);
        jScrollPane1.setViewportView(jTextAreaQuerys);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabelManejo.setBackground(new java.awt.Color(51, 153, 255));
        jLabelManejo.setText("MANEJAR CONEXIÓN CON LA BBDD");
        jLabelManejo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelManejo.setOpaque(true);

        jButton_Conectar.setBackground(new java.awt.Color(0, 204, 204));
        jButton_Conectar.setText("Conectar/Actualizar");
        jButton_Conectar.setBorder(new javax.swing.border.MatteBorder(null));
        jButton_Conectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConectarActionPerformed(evt);
            }
        });

        jButton_Desconectar.setBackground(new java.awt.Color(0, 204, 204));
        jButton_Desconectar.setText("Desconectar");
        jButton_Desconectar.setBorder(new javax.swing.border.MatteBorder(null));
        jButton_Desconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DesconectarActionPerformed(evt);
            }
        });

        jTabbedPane1.setBackground(new java.awt.Color(0, 102, 102));

        jPanel_Selects.setBackground(new java.awt.Color(0, 153, 204));
        jPanel_Selects.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel_SelectEquipo.setBackground(new java.awt.Color(102, 255, 255));
        jLabel_SelectEquipo.setText("CONSULTAR EQUIPOS");
        jLabel_SelectEquipo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_SelectEquipo.setOpaque(true);

        jLabel_SelectDatos.setBackground(new java.awt.Color(102, 255, 255));
        jLabel_SelectDatos.setText("CONSULTAR DATOS DEL EQUIPO");
        jLabel_SelectDatos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_SelectDatos.setOpaque(true);

        jLabel_SelectSuperBowls.setBackground(new java.awt.Color(102, 255, 255));
        jLabel_SelectSuperBowls.setText("CONSULTAR SUPER BOWLS DEL EQUIPO");
        jLabel_SelectSuperBowls.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_SelectSuperBowls.setOpaque(true);

        jButton_ConsultaEquipos.setBackground(new java.awt.Color(0, 204, 204));
        jButton_ConsultaEquipos.setText("EJECUTAR CONSULTA");
        jButton_ConsultaEquipos.setBorder(new javax.swing.border.MatteBorder(null));
        jButton_ConsultaEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConsultaEquiposActionPerformed(evt);
            }
        });

        jButton_ConsultaDatos.setBackground(new java.awt.Color(0, 204, 204));
        jButton_ConsultaDatos.setText("EJECUTAR CONSULTA");
        jButton_ConsultaDatos.setBorder(new javax.swing.border.MatteBorder(null));
        jButton_ConsultaDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConsultaDatosActionPerformed(evt);
            }
        });

        jButton_ConsultaSB.setBackground(new java.awt.Color(0, 204, 204));
        jButton_ConsultaSB.setText("EJECUTAR CONSULTA");
        jButton_ConsultaSB.setBorder(new javax.swing.border.MatteBorder(null));
        jButton_ConsultaSB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConsultaSBActionPerformed(evt);
            }
        });

        jLabel_SelectSuperBowls1.setBackground(new java.awt.Color(102, 255, 255));
        jLabel_SelectSuperBowls1.setText("BUSCAR EQUIPO");
        jLabel_SelectSuperBowls1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_SelectSuperBowls1.setOpaque(true);

        jTextField_BuscarEquipo.setBackground(new java.awt.Color(0, 51, 102));
        jTextField_BuscarEquipo.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_BuscarEquipo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton_Buscar.setBackground(new java.awt.Color(0, 204, 204));
        jButton_Buscar.setText("EJECUTAR CONSULTA");
        jButton_Buscar.setBorder(new javax.swing.border.MatteBorder(null));
        jButton_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_SelectsLayout = new javax.swing.GroupLayout(jPanel_Selects);
        jPanel_Selects.setLayout(jPanel_SelectsLayout);
        jPanel_SelectsLayout.setHorizontalGroup(
            jPanel_SelectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SelectsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_SelectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_SelectsLayout.createSequentialGroup()
                        .addGroup(jPanel_SelectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_SelectSuperBowls1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_SelectSuperBowls, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .addComponent(jLabel_SelectDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_SelectEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_SelectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel_SelectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton_ConsultaEquipos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                .addComponent(jButton_ConsultaDatos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_ConsultaSB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jTextField_BuscarEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        jPanel_SelectsLayout.setVerticalGroup(
            jPanel_SelectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SelectsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_SelectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_SelectEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_ConsultaEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_SelectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_SelectDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_ConsultaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_SelectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_SelectSuperBowls, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_ConsultaSB, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_SelectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_SelectSuperBowls1, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jTextField_BuscarEquipo))
                .addGap(18, 18, 18)
                .addComponent(jButton_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CONSULTAR BBDD", jPanel_Selects);

        jPanel_Updates.setBackground(new java.awt.Color(0, 153, 204));
        jPanel_Updates.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jComboBox_Equipos.setBackground(new java.awt.Color(0, 51, 102));
        jComboBox_Equipos.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox_Equipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel_SelecionarEquipo.setBackground(new java.awt.Color(102, 255, 255));
        jLabel_SelecionarEquipo.setText("SELECCIONAR EQUIPO A MODIFICAR");
        jLabel_SelecionarEquipo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_SelecionarEquipo.setOpaque(true);

        jLabel_CambiarNombre.setBackground(new java.awt.Color(102, 255, 255));
        jLabel_CambiarNombre.setText("NOMBRE NUEVO");
        jLabel_CambiarNombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_CambiarNombre.setOpaque(true);

        jLabel_CambiarCiudad.setBackground(new java.awt.Color(102, 255, 255));
        jLabel_CambiarCiudad.setText("CIUDAD NUEVA");
        jLabel_CambiarCiudad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_CambiarCiudad.setOpaque(true);

        jLabel_CambiarEstadio.setBackground(new java.awt.Color(102, 255, 255));
        jLabel_CambiarEstadio.setText("ESTADIO NUEVO");
        jLabel_CambiarEstadio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_CambiarEstadio.setOpaque(true);

        jTextField_UpdateNombre.setBackground(new java.awt.Color(0, 51, 102));
        jTextField_UpdateNombre.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_UpdateNombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextField_UpdateCiudad.setBackground(new java.awt.Color(0, 51, 102));
        jTextField_UpdateCiudad.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_UpdateCiudad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextField_UpdateEstadio.setBackground(new java.awt.Color(0, 51, 102));
        jTextField_UpdateEstadio.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_UpdateEstadio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton_UPDATEEquipo.setBackground(new java.awt.Color(0, 204, 204));
        jButton_UPDATEEquipo.setText("EJECUTAR");
        jButton_UPDATEEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UPDATEEquipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_UpdatesLayout = new javax.swing.GroupLayout(jPanel_Updates);
        jPanel_Updates.setLayout(jPanel_UpdatesLayout);
        jPanel_UpdatesLayout.setHorizontalGroup(
            jPanel_UpdatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_UpdatesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_UpdatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_CambiarEstadio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_CambiarCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_CambiarNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_SelecionarEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_UpdatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_UpdatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField_UpdateEstadio)
                        .addComponent(jTextField_UpdateCiudad, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField_UpdateNombre, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jComboBox_Equipos, javax.swing.GroupLayout.Alignment.LEADING, 0, 192, Short.MAX_VALUE))
                    .addComponent(jButton_UPDATEEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jPanel_UpdatesLayout.setVerticalGroup(
            jPanel_UpdatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_UpdatesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_UpdatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox_Equipos)
                    .addComponent(jLabel_SelecionarEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_UpdatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_CambiarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_UpdateNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_UpdatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_CambiarCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jTextField_UpdateCiudad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_UpdatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_CambiarEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_UpdateEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_UPDATEEquipo)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("MODIFICAR EQUIPOS", jPanel_Updates);

        jPanel_Inserts.setBackground(new java.awt.Color(0, 153, 204));
        jPanel_Inserts.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel_InsertarDatos.setBackground(new java.awt.Color(0, 153, 153));

        jLabel_Conferencia.setBackground(new java.awt.Color(102, 255, 255));
        jLabel_Conferencia.setText("CONFERENCIA");
        jLabel_Conferencia.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_Conferencia.setOpaque(true);

        jLabel_Division.setBackground(new java.awt.Color(102, 255, 255));
        jLabel_Division.setText("DIVISIÓN");
        jLabel_Division.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_Division.setOpaque(true);

        jLabel_Propietario.setBackground(new java.awt.Color(102, 255, 255));
        jLabel_Propietario.setText("PROPIETARIO");
        jLabel_Propietario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_Propietario.setOpaque(true);

        jLabel_Fundacion.setBackground(new java.awt.Color(102, 255, 255));
        jLabel_Fundacion.setText("FUNDACIÓN");
        jLabel_Fundacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_Fundacion.setOpaque(true);

        jLabel_EntradaNFL.setBackground(new java.awt.Color(102, 255, 255));
        jLabel_EntradaNFL.setText("ENTRADA EN LA NFL");
        jLabel_EntradaNFL.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_EntradaNFL.setOpaque(true);

        jLabel_CodIDDATOS.setBackground(new java.awt.Color(102, 255, 255));
        jLabel_CodIDDATOS.setText("CÓDIGO IDENTIFICADOR");
        jLabel_CodIDDATOS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_CodIDDATOS.setOpaque(true);

        jTextField_Conferencia.setBackground(new java.awt.Color(0, 51, 102));
        jTextField_Conferencia.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Conferencia.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextField_Division.setBackground(new java.awt.Color(0, 51, 102));
        jTextField_Division.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Division.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextField_Propietario.setBackground(new java.awt.Color(0, 51, 102));
        jTextField_Propietario.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Propietario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextField_Fundacion.setBackground(new java.awt.Color(0, 51, 102));
        jTextField_Fundacion.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Fundacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextField_EntradaNFL.setBackground(new java.awt.Color(0, 51, 102));
        jTextField_EntradaNFL.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_EntradaNFL.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextField_CodIDDATOS.setBackground(new java.awt.Color(0, 51, 102));
        jTextField_CodIDDATOS.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_CodIDDATOS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton_InsertarDatos.setBackground(new java.awt.Color(0, 204, 204));
        jButton_InsertarDatos.setText("INSERTAR");
        jButton_InsertarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_InsertarDatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_InsertarDatosLayout = new javax.swing.GroupLayout(jPanel_InsertarDatos);
        jPanel_InsertarDatos.setLayout(jPanel_InsertarDatosLayout);
        jPanel_InsertarDatosLayout.setHorizontalGroup(
            jPanel_InsertarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_InsertarDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_InsertarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_InsertarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_InsertarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_InsertarDatosLayout.createSequentialGroup()
                            .addComponent(jLabel_Conferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField_Conferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel_InsertarDatosLayout.createSequentialGroup()
                            .addComponent(jLabel_Division, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField_Division, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel_InsertarDatosLayout.createSequentialGroup()
                            .addComponent(jLabel_Propietario, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField_Propietario, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel_InsertarDatosLayout.createSequentialGroup()
                            .addComponent(jLabel_Fundacion, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField_Fundacion, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel_InsertarDatosLayout.createSequentialGroup()
                            .addComponent(jLabel_EntradaNFL, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField_EntradaNFL, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel_InsertarDatosLayout.createSequentialGroup()
                            .addComponent(jLabel_CodIDDATOS, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField_CodIDDATOS, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        jPanel_InsertarDatosLayout.setVerticalGroup(
            jPanel_InsertarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_InsertarDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_InsertarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Conferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Conferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_InsertarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Division, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Division, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_InsertarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Propietario, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Propietario, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_InsertarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Fundacion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Fundacion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_InsertarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_EntradaNFL, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_EntradaNFL, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_InsertarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_CodIDDATOS, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_CodIDDATOS, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton_InsertarDatos)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jTabbedPane_Inserts.addTab("DATOS DE EQUIPO", jPanel_InsertarDatos);

        jPanel_InsertarSuperBowls.setBackground(new java.awt.Color(0, 153, 153));

        jLabel_FechaVict.setBackground(new java.awt.Color(102, 255, 255));
        jLabel_FechaVict.setText("FECHA DE LAS VICTORIAS");
        jLabel_FechaVict.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_FechaVict.setOpaque(true);

        jLabel_CantidadVict.setBackground(new java.awt.Color(102, 255, 255));
        jLabel_CantidadVict.setText("CANTIDAD DE VICTORIAS");
        jLabel_CantidadVict.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_CantidadVict.setOpaque(true);

        jLabel_CodIDSB.setBackground(new java.awt.Color(102, 255, 255));
        jLabel_CodIDSB.setText("CÓDIGO IDENTIFICADOR");
        jLabel_CodIDSB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_CodIDSB.setOpaque(true);

        jTextField_FechaVict.setBackground(new java.awt.Color(0, 51, 102));
        jTextField_FechaVict.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_FechaVict.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextField_CantidadVict.setBackground(new java.awt.Color(0, 51, 102));
        jTextField_CantidadVict.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_CantidadVict.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextField_CodIDSB.setBackground(new java.awt.Color(0, 51, 102));
        jTextField_CodIDSB.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_CodIDSB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton_InsertarSB.setBackground(new java.awt.Color(0, 204, 204));
        jButton_InsertarSB.setText("INSERTAR");
        jButton_InsertarSB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_InsertarSBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_InsertarSuperBowlsLayout = new javax.swing.GroupLayout(jPanel_InsertarSuperBowls);
        jPanel_InsertarSuperBowls.setLayout(jPanel_InsertarSuperBowlsLayout);
        jPanel_InsertarSuperBowlsLayout.setHorizontalGroup(
            jPanel_InsertarSuperBowlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_InsertarSuperBowlsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_InsertarSuperBowlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_InsertarSB, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_InsertarSuperBowlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_InsertarSuperBowlsLayout.createSequentialGroup()
                            .addComponent(jLabel_FechaVict, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField_FechaVict, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel_InsertarSuperBowlsLayout.createSequentialGroup()
                            .addComponent(jLabel_CantidadVict, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField_CantidadVict, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel_InsertarSuperBowlsLayout.createSequentialGroup()
                            .addComponent(jLabel_CodIDSB, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField_CodIDSB, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        jPanel_InsertarSuperBowlsLayout.setVerticalGroup(
            jPanel_InsertarSuperBowlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_InsertarSuperBowlsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_InsertarSuperBowlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_FechaVict, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_FechaVict, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_InsertarSuperBowlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_CantidadVict, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_CantidadVict, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_InsertarSuperBowlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_CodIDSB, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_CodIDSB, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton_InsertarSB)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        jTabbedPane_Inserts.addTab("SUPER BOWLS DEL EQUIPO", jPanel_InsertarSuperBowls);

        jPanel_InsertarEquipos.setBackground(new java.awt.Color(0, 153, 153));

        jLabel_Nombre.setBackground(new java.awt.Color(102, 255, 255));
        jLabel_Nombre.setText("NOMBRE DEL EQUIPO");
        jLabel_Nombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_Nombre.setOpaque(true);

        jLabel_Ciudad.setBackground(new java.awt.Color(102, 255, 255));
        jLabel_Ciudad.setText("CIUDAD DE RESIDENCIA");
        jLabel_Ciudad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_Ciudad.setOpaque(true);

        jLabel_Estadio.setBackground(new java.awt.Color(102, 255, 255));
        jLabel_Estadio.setText("ESTADIO DEL EQUIPO");
        jLabel_Estadio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_Estadio.setOpaque(true);

        jLabel_CodIDEQUIPO.setBackground(new java.awt.Color(102, 255, 255));
        jLabel_CodIDEQUIPO.setText("CÓDIGO IDENTIFICADOR");
        jLabel_CodIDEQUIPO.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_CodIDEQUIPO.setOpaque(true);

        jLabel_Datos.setBackground(new java.awt.Color(102, 255, 255));
        jLabel_Datos.setText("DATOS DEL EQUIPO");
        jLabel_Datos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_Datos.setOpaque(true);

        jLabel_SuperBowls.setBackground(new java.awt.Color(102, 255, 255));
        jLabel_SuperBowls.setText("SUPER BOWLS DEL EQUIPO");
        jLabel_SuperBowls.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_SuperBowls.setOpaque(true);

        jTextField_Nombre.setBackground(new java.awt.Color(0, 51, 102));
        jTextField_Nombre.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Nombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextField_Ciudad.setBackground(new java.awt.Color(0, 51, 102));
        jTextField_Ciudad.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Ciudad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextField_Estadio.setBackground(new java.awt.Color(0, 51, 102));
        jTextField_Estadio.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Estadio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextField_CodIDEQUIPO.setBackground(new java.awt.Color(0, 51, 102));
        jTextField_CodIDEQUIPO.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_CodIDEQUIPO.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jComboBox_Datos.setBackground(new java.awt.Color(0, 51, 102));
        jComboBox_Datos.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox_Datos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox_SuperBowls.setBackground(new java.awt.Color(0, 51, 102));
        jComboBox_SuperBowls.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox_SuperBowls.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton_InsertarEquipo.setBackground(new java.awt.Color(0, 204, 204));
        jButton_InsertarEquipo.setText("INSERTAR");
        jButton_InsertarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_InsertarEquipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_InsertarEquiposLayout = new javax.swing.GroupLayout(jPanel_InsertarEquipos);
        jPanel_InsertarEquipos.setLayout(jPanel_InsertarEquiposLayout);
        jPanel_InsertarEquiposLayout.setHorizontalGroup(
            jPanel_InsertarEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_InsertarEquiposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_InsertarEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_InsertarEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_InsertarEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel_InsertarEquiposLayout.createSequentialGroup()
                            .addComponent(jLabel_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel_InsertarEquiposLayout.createSequentialGroup()
                            .addComponent(jLabel_Ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField_Ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel_InsertarEquiposLayout.createSequentialGroup()
                            .addComponent(jLabel_Estadio, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField_Estadio, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel_InsertarEquiposLayout.createSequentialGroup()
                            .addComponent(jLabel_CodIDEQUIPO, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField_CodIDEQUIPO, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel_InsertarEquiposLayout.createSequentialGroup()
                            .addComponent(jLabel_Datos, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBox_Datos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel_InsertarEquiposLayout.createSequentialGroup()
                            .addComponent(jLabel_SuperBowls, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBox_SuperBowls, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        jPanel_InsertarEquiposLayout.setVerticalGroup(
            jPanel_InsertarEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_InsertarEquiposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_InsertarEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_InsertarEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_InsertarEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Estadio, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Estadio, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_InsertarEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_CodIDEQUIPO, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_CodIDEQUIPO, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_InsertarEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Datos, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_Datos, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_InsertarEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_SuperBowls, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_SuperBowls, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton_InsertarEquipo)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jTabbedPane_Inserts.addTab("EQUIPO", jPanel_InsertarEquipos);

        javax.swing.GroupLayout jPanel_InsertsLayout = new javax.swing.GroupLayout(jPanel_Inserts);
        jPanel_Inserts.setLayout(jPanel_InsertsLayout);
        jPanel_InsertsLayout.setHorizontalGroup(
            jPanel_InsertsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_Inserts)
        );
        jPanel_InsertsLayout.setVerticalGroup(
            jPanel_InsertsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_Inserts)
        );

        jTabbedPane1.addTab("INSERTAR EN LA BBDD", jPanel_Inserts);

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));

        jLabel_BorrarEquipo.setBackground(new java.awt.Color(102, 255, 255));
        jLabel_BorrarEquipo.setText("NOMBRE DEL EQUIPO");
        jLabel_BorrarEquipo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_BorrarEquipo.setOpaque(true);

        jTextField_BorrarEquipo.setBackground(new java.awt.Color(0, 51, 102));
        jTextField_BorrarEquipo.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_BorrarEquipo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton_Borrar.setBackground(new java.awt.Color(0, 204, 204));
        jButton_Borrar.setText("BORRAR");
        jButton_Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_Borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel_BorrarEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_BorrarEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_BorrarEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_BorrarEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton_Borrar)
                .addContainerGap(254, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("BORRAR EQUIPO", jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelManejo, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Conectar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Desconectar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelManejo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Conectar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Desconectar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_DesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DesconectarActionPerformed
        ges.cerrar_conexion();
        deshabilitarBotones();
    }//GEN-LAST:event_jButton_DesconectarActionPerformed

    //este botón sirve a su vez para conectar con el servidor/bbdd como para actualizar la conexión en caso de cambios
    private void jButton_ConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConectarActionPerformed

        if (ges.GestorConexion() == 0) {
            System.out.println("Conexión establecida correctamente");
            rellenarBoxEquipos();
            rellenarBoxDatos();
            rellenarBoxSB();
            conectar();
        } else if (ges.GestorConexion() == 1) {
            System.out.println("No fue posible establecer una conexión");
        } else {
            System.out.println("Error en la conexion");
        }
    }//GEN-LAST:event_jButton_ConectarActionPerformed

    private void jButton_ConsultaEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConsultaEquiposActionPerformed
        jDialog1.setVisible(true);
        jTextAreaQuerys.setText(ges.selectEquipos());
    }//GEN-LAST:event_jButton_ConsultaEquiposActionPerformed

    private void jButton_ConsultaDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConsultaDatosActionPerformed
        jDialog1.setVisible(true);
        jTextAreaQuerys.setText(ges.selectDatos());
    }//GEN-LAST:event_jButton_ConsultaDatosActionPerformed

    private void jButton_ConsultaSBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConsultaSBActionPerformed
        jDialog1.setVisible(true);
        jTextAreaQuerys.setText(ges.selectSB());
    }//GEN-LAST:event_jButton_ConsultaSBActionPerformed

    private void jButton_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuscarActionPerformed
        jDialog1.setVisible(true);
        jTextAreaQuerys.setText(ges.buscarEquipo(jTextField_BuscarEquipo.getText()));
        jTextField_BuscarEquipo.setText("");
    }//GEN-LAST:event_jButton_BuscarActionPerformed

    private void jButton_UPDATEEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UPDATEEquipoActionPerformed
        String idEquipo = (String) jComboBox_Equipos.getSelectedItem();
        int equipo = Integer.parseInt(idEquipo.split(" ")[0]);
        ges.modificarEquipo(jTextField_UpdateNombre.getText(), jTextField_UpdateCiudad.getText(), jTextField_UpdateEstadio.getText(), equipo);
        jTextField_UpdateNombre.setText("");
        jTextField_UpdateCiudad.setText("");
        jTextField_UpdateEstadio.setText("");
    }//GEN-LAST:event_jButton_UPDATEEquipoActionPerformed

    private void jButton_InsertarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_InsertarDatosActionPerformed
        ges.insertarDatosEquipo(jTextField_Conferencia.getText(), jTextField_Division.getText(), jTextField_Propietario.getText(),
                jTextField_Fundacion.getText(), jTextField_EntradaNFL.getText(), Integer.parseInt(jTextField_CodIDDATOS.getText()));
        jTextField_Conferencia.setText("");
        jTextField_Division.setText("");
        jTextField_Propietario.setText("");
        jTextField_Fundacion.setText("");
        jTextField_EntradaNFL.setText("");
        jTextField_CodIDDATOS.setText("");
    }//GEN-LAST:event_jButton_InsertarDatosActionPerformed

    private void jButton_InsertarSBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_InsertarSBActionPerformed
        ges.insertarSuperBowls(jTextField_FechaVict.getText(), jTextField_CantidadVict.getText(), Integer.parseInt(jTextField_CodIDSB.getText()));
        jTextField_FechaVict.setText("");
        jTextField_CantidadVict.setText("");
        jTextField_CodIDSB.setText("");
    }//GEN-LAST:event_jButton_InsertarSBActionPerformed

    private void jButton_InsertarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_InsertarEquipoActionPerformed
        String datos = (String) jComboBox_Datos.getSelectedItem();
        int dato = Integer.parseInt(datos.split(" ")[0]);
        String sb = (String) jComboBox_SuperBowls.getSelectedItem();
        int superBowl = Integer.parseInt(sb.split(" ")[0]);
        ges.insertarEquipo(Integer.parseInt(jTextField_CodIDEQUIPO.getText()), jTextField_Nombre.getText(),
                jTextField_Ciudad.getText(), jTextField_Estadio.getText(), dato, superBowl);
        jTextField_CodIDEQUIPO.setText("");
        jTextField_Nombre.setText("");
        jTextField_Ciudad.setText("");
        jTextField_Estadio.setText("");
    }//GEN-LAST:event_jButton_InsertarEquipoActionPerformed

    private void jButton_BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BorrarActionPerformed
        ges.borrarEquipo(jTextField_BorrarEquipo.getText());
        jTextField_BorrarEquipo.setText("");
    }//GEN-LAST:event_jButton_BorrarActionPerformed

    //este método rellena los combobox relacionados a los equipos con el método arraylist creado en la clase del gestor
    private void rellenarBoxEquipos() {
        //primero eimina los datos por defecto para llenarlos con los datos deseados
        jComboBox_Equipos.removeAllItems();
        ArrayList<String> listaEquipos = new ArrayList<String>();//para la foreign key de album en canciones
        listaEquipos = ges.comboBoxEquipos();
        for (int i = 0; i < listaEquipos.size(); i++) {
            jComboBox_Equipos.addItem(listaEquipos.get(i));
        }
    }

    private void rellenarBoxDatos() {
        //primero eimina los datos por defecto para llenarlos con los datos deseados
        jComboBox_Datos.removeAllItems();
        ArrayList<String> listaEquipos = new ArrayList<String>();//para la foreign key de album en canciones
        listaEquipos = ges.comboBoxDatos();
        for (int i = 0; i < listaEquipos.size(); i++) {
            jComboBox_Datos.addItem(listaEquipos.get(i));
        }
    }

    private void rellenarBoxSB() {
        //primero eimina los datos por defecto para llenarlos con los datos deseados
        jComboBox_SuperBowls.removeAllItems();
        ArrayList<String> listaEquipos = new ArrayList<String>();
        listaEquipos = ges.comboBoxSuperBowls();
        for (int i = 0; i < listaEquipos.size(); i++) {
            jComboBox_SuperBowls.addItem(listaEquipos.get(i));
        }
    }

    //este método deshabilita todos los botones y vacia los combobox en caso de no estar conectado a la bbdd o de haber
    //finalizado la conexión
    private void deshabilitarBotones() {
        jButton_Desconectar.setEnabled(false);
        jButton_Borrar.setEnabled(false);
        jButton_Buscar.setEnabled(false);
        jButton_ConsultaDatos.setEnabled(false);
        jButton_ConsultaEquipos.setEnabled(false);
        jButton_ConsultaSB.setEnabled(false);
        jButton_InsertarDatos.setEnabled(false);
        jButton_InsertarEquipo.setEnabled(false);
        jButton_InsertarSB.setEnabled(false);
        jButton_UPDATEEquipo.setEnabled(false);
        jTabbedPane1.setEnabled(false);
    }

    //este método habilita todos los botones de la interfaz despues de haber conectado con la base de datos
    private void conectar() {
        jButton_Desconectar.setEnabled(true);
        jButton_Borrar.setEnabled(true);
        jButton_Buscar.setEnabled(true);
        jButton_ConsultaDatos.setEnabled(true);
        jButton_ConsultaEquipos.setEnabled(true);
        jButton_ConsultaSB.setEnabled(true);
        jButton_InsertarDatos.setEnabled(true);
        jButton_InsertarEquipo.setEnabled(true);
        jButton_InsertarSB.setEnabled(true);
        jButton_UPDATEEquipo.setEnabled(true);
        jTabbedPane1.setEnabled(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Borrar;
    private javax.swing.JButton jButton_Buscar;
    private javax.swing.JButton jButton_Conectar;
    private javax.swing.JButton jButton_ConsultaDatos;
    private javax.swing.JButton jButton_ConsultaEquipos;
    private javax.swing.JButton jButton_ConsultaSB;
    private javax.swing.JButton jButton_Desconectar;
    private javax.swing.JButton jButton_InsertarDatos;
    private javax.swing.JButton jButton_InsertarEquipo;
    private javax.swing.JButton jButton_InsertarSB;
    private javax.swing.JButton jButton_UPDATEEquipo;
    private javax.swing.JComboBox<String> jComboBox_Datos;
    private javax.swing.JComboBox<String> jComboBox_Equipos;
    private javax.swing.JComboBox<String> jComboBox_SuperBowls;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabelManejo;
    private javax.swing.JLabel jLabel_BorrarEquipo;
    private javax.swing.JLabel jLabel_CambiarCiudad;
    private javax.swing.JLabel jLabel_CambiarEstadio;
    private javax.swing.JLabel jLabel_CambiarNombre;
    private javax.swing.JLabel jLabel_CantidadVict;
    private javax.swing.JLabel jLabel_Ciudad;
    private javax.swing.JLabel jLabel_CodIDDATOS;
    private javax.swing.JLabel jLabel_CodIDEQUIPO;
    private javax.swing.JLabel jLabel_CodIDSB;
    private javax.swing.JLabel jLabel_Conferencia;
    private javax.swing.JLabel jLabel_Datos;
    private javax.swing.JLabel jLabel_Division;
    private javax.swing.JLabel jLabel_EntradaNFL;
    private javax.swing.JLabel jLabel_Estadio;
    private javax.swing.JLabel jLabel_FechaVict;
    private javax.swing.JLabel jLabel_Fundacion;
    private javax.swing.JLabel jLabel_Nombre;
    private javax.swing.JLabel jLabel_Propietario;
    private javax.swing.JLabel jLabel_SelecionarEquipo;
    private javax.swing.JLabel jLabel_SelectDatos;
    private javax.swing.JLabel jLabel_SelectEquipo;
    private javax.swing.JLabel jLabel_SelectSuperBowls;
    private javax.swing.JLabel jLabel_SelectSuperBowls1;
    private javax.swing.JLabel jLabel_SuperBowls;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_InsertarDatos;
    private javax.swing.JPanel jPanel_InsertarEquipos;
    private javax.swing.JPanel jPanel_InsertarSuperBowls;
    private javax.swing.JPanel jPanel_Inserts;
    private javax.swing.JPanel jPanel_Selects;
    private javax.swing.JPanel jPanel_Updates;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane_Inserts;
    private javax.swing.JTextArea jTextAreaQuerys;
    private javax.swing.JTextField jTextField_BorrarEquipo;
    private javax.swing.JTextField jTextField_BuscarEquipo;
    private javax.swing.JTextField jTextField_CantidadVict;
    private javax.swing.JTextField jTextField_Ciudad;
    private javax.swing.JTextField jTextField_CodIDDATOS;
    private javax.swing.JTextField jTextField_CodIDEQUIPO;
    private javax.swing.JTextField jTextField_CodIDSB;
    private javax.swing.JTextField jTextField_Conferencia;
    private javax.swing.JTextField jTextField_Division;
    private javax.swing.JTextField jTextField_EntradaNFL;
    private javax.swing.JTextField jTextField_Estadio;
    private javax.swing.JTextField jTextField_FechaVict;
    private javax.swing.JTextField jTextField_Fundacion;
    private javax.swing.JTextField jTextField_Nombre;
    private javax.swing.JTextField jTextField_Propietario;
    private javax.swing.JTextField jTextField_UpdateCiudad;
    private javax.swing.JTextField jTextField_UpdateEstadio;
    private javax.swing.JTextField jTextField_UpdateNombre;
    // End of variables declaration//GEN-END:variables

}
